sudo: false
language: node_js
node_js:
- iojs
- '0.12'
- '0.10'
deploy:
  provider: npm
  email: john@prometheas.com
  api_key:
    secure: c2Aqs7mSmbFrzoklXyyD5KPvgeyNWAtt3VhifI6zDC/teV5xulnRgrZAxkSXk3MMOC86qhQ7JH3UCALtVGsi9zlxkkWrajdi9WRM1Xhxf2Z0zxop/MhKnycC3N13J9rhYb9ByZWvNskFw+zZGvyLmUFt7SJzzXgeAR6bIbhrUtA=
  on:
    repo: prometheas/generator-multistack-tdd-kata
    branch: develop
